/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#313032",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c8c5cb",
        "outline-variant": "#3c494e",
        "on-primary-container": "#00566a",
        "primary-fixed-dim": "#4cd6ff",
        "error-container": "#93000a",
        "secondary-container": "#7d01b1",
        "primary": "#a4e6ff",
        "surface-dim": "#131315",
        "outline": "#859399",
        "surface-container-low": "#1b1b1d",
        "on-secondary-fixed-variant": "#7200a3",
        "secondary-fixed": "#f6d9ff",
        "surface-container-high": "#2a2a2c",
        "on-secondary-fixed": "#310048",
        "on-background": "#e5e1e4",
        "surface-tint": "#4cd6ff",
        "inverse-surface": "#e5e1e4",
        "on-primary-fixed": "#001f28",
        "inverse-primary": "#00677f",
        "on-tertiary": "#303034",
        "error": "#ffb4ab",
        "surface": "#131315",
        "on-surface-variant": "#bbc9cf",
        "tertiary-container": "#c2bfc5",
        "secondary": "#e9b3ff",
        "on-secondary-container": "#e5a9ff",
        "background": "#131315",
        "surface-container": "#201f21",
        "on-tertiary-fixed-variant": "#47464b",
        "surface-bright": "#39393b",
        "on-surface": "#e5e1e4",
        "on-tertiary-fixed": "#1b1b1f",
        "surface-variant": "#353437",
        "tertiary-fixed": "#e4e1e7",
        "primary-fixed": "#b7eaff",
        "surface-container-lowest": "#0e0e10",
        "on-secondary": "#510074",
        "tertiary": "#dedbe0",
        "secondary-fixed-dim": "#e9b3ff",
        "surface-container-highest": "#353437",
        "on-tertiary-container": "#4e4e52",
        "on-primary-fixed-variant": "#004e60",
        "primary-container": "#00d1ff",
        "on-error": "#690005",
        "on-primary": "#003543"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "container-padding": "32px",
        "sidebar-width-expanded": "280px",
        "card-padding": "24px",
        "gutter": "24px",
        "sidebar-width-collapsed": "80px"
      },
      fontFamily: {
        "h2": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "h1": ["Plus Jakarta Sans", "sans-serif"],
        "h3": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "code": ["Inter", "monospace"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "h2": ["32px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-sm": ["13px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "h1": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "h3": ["24px", { "lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }],
        "code": ["14px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
